Python for Data Science

Опис завдання:

Створити pandas DataFrame (**використовуючи метод створення датафрейму на основі словника**)для зберігання інформації про продукти в магазині.

Включити наступні стовпці:

"Назва продукту" (рядки): Назва продукту.

"Ціна" (числа з рухомою комою): Ціна продукту в гривнях.

"Кількість на складі" (цілі числа): Кількість одиниць продукту, доступних на складі.

"Категорія" (рядки): Категорія або тип продукту.

Додати кілька продуктів до DataFrame, заповнивши відповідні стовпці.
Вивести створений DataFrame на екран для перевірки.

Приклад вмісту DataFrame (після створення):

    Назва продукту   Ціна   Кількість на складі   Категорія

    0   Яблука          2.5            100            Фрукти

    1   Банани          1.2             50            Фрукти

    2   Апельсини       1.8             75            Фрукти

    3   Груші           2.0             60            Фрукти

In [10]:
import pandas as pd

data = {
    'Назва продукту': ['Яблука', 'Банани', 'Апельсини', 'Груші'],
    'Ціна': [2.5, 1.2, 1.8, 2.0],
    'Кількість на складі': [100, 50, 75, 60],
    'Категорія': ['Фрукти', 'Фрукти', 'Фрукти', 'Фрукти']
}

df = pd.DataFrame(data)
print(df)

  Назва продукту  Ціна  Кількість на складі Категорія
0         Яблука   2.5                  100    Фрукти
1         Банани   1.2                   50    Фрукти
2      Апельсини   1.8                   75    Фрукти
3          Груші   2.0                   60    Фрукти

Опис завдання:

Створіть pandas DataFrame (**використовуючи метод створення датафрейму з списку зі списками**) для зберігання інформації про студентів вашого університету.

Включіть наступні стовпці:

"Ім'я" (рядки): Ім'я студента.

"Прізвище" (рядки): Прізвище студента.

"Вік" (цілі числа): Вік студента.

"Спеціальність" (рядки): Спеціальність, на яку навчається студент.

"Середній бал" (числа з рухомою комою): Середній бал студента.

Приклад вмісту DataFrame (після створення):

    Ім'я    Прізвище  Вік         Спеціальність   Середній бал
    0  John   Smith     20   Інформатика         88.5
    1  Alice  Johnson   22   Економіка            75.0
    2  Emma   Brown     21   Психологія           92.3
    3  David  Lee       23   Медицина             78.8

In [6]:
import pandas as pd

data = [
    ['John', 'Smith', 20, 'Інформатика', 88.5],
    ['Alice', 'Johnson', 22, 'Економіка', 75.0],
    ['Emma', 'Brown', 21, 'Психологія', 92.3],
    ['David', 'Lee', 23, 'Медицина', 78.8]
]

df = pd.DataFrame(data, columns=['Ім\'я', 'Прізвище', 'Вік', 'Спеціальність', 'Середній бал'])
print(df)

    Ім'я Прізвище  Вік Спеціальність  Середній бал
0   John    Smith   20   Інформатика          88.5
1  Alice  Johnson   22     Економіка          75.0
2   Emma    Brown   21    Психологія          92.3
3  David      Lee   23      Медицина          78.8

Опис завдання:

Створіть pandas DataFrame для зберігання інформації про фільми.

Включіть наступні стовпці:

"Назва фільму" (рядки): Назва фільму.

"Рік випуску" (цілі числа): Рік випуску фільму.

"Жанр" (рядки): Жанр фільму, наприклад, "драма," "комедія," "фантастика" і т.д.

"Рейтинг" (числа з рухомою комою): Рейтинг фільму.

Додайте інформацію про кілька фільмів до DataFrame, заповнивши відповідні стовпці.

Змініть стандартну індексацію на стовпець "Назва фільму".

Виведіть створений DataFrame на екран для перевірки.

Приклад вмісту DataFrame (після створення):

    Назва фільму           Рік випуску   Жанр       Рейтинг
    Форрест Гамп              1994      Драма         8.8
    Месники                   2012      Фантастика    8.5
    Просто Кров               2007      Кримінал      9.0
    Темний Лицар              2008      Драма         9.2

In [9]:
import pandas as pd

data = {
    'Назва фільму': ['Форрест Гамп', 'Месники', 'Просто Кров', 'Темний Лицар'],
    'Рік випуску': [1994, 2012, 2007, 2008],
    'Жанр': ['Драма', 'Фантастика', 'Кримінал', 'Драма'],
    'Рейтинг': [8.8, 8.5, 9.0, 9.2]
}


df = pd.DataFrame(data)
df.set_index('Назва фільму', inplace=True)
print(df.to_string())

              Рік випуску        Жанр  Рейтинг
Назва фільму
Форрест Гамп         1994       Драма      8.8
Месники              2012  Фантастика      8.5
Просто Кров          2007    Кримінал      9.0
Темний Лицар         2008       Драма      9.2